Components/CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using soppi.Interfaces;

public class CategoryViewComponent : ViewComponent {
    private readonly ICategoryService _categoryService;

    public CategoryViewComponent(ICategoryService categoryService) {
        _categoryService = categoryService;
    }

    public async Task<IViewComponentResult> InvokeAsync() {
        var categories = await _categoryService.GetAll();
        return View(categories);
    }
}

Controllers/OrderController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using soppi.Data;
using soppi.Interfaces;
using soppi.Models;
using soppi.Models.ViewModel;

namespace soppi.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly INotyfService _notyf;

        public OrderController(IOrderService orderService, INotyfService notyf, SignInManager<ApplicationUser> signInManager)
        {
            _orderService = orderService;
            _notyf = notyf;
            _signInManager = signInManager;
        }
        public async Task<IActionResult> Index()
        {
            var orders = await _orderService.GetAllOrdersByUser();
            return View(orders);

        }
        [HttpPost]
        public async Task<IActionResult> Add(OrderViewModel order)
        {
            var rs = await _orderService.CreateOrder(order);
            if (rs is OkResult)
            {
                _notyf.Success("Đặt hàng thành công!");
                return RedirectToAction("Detail", "Product", new { id = order.ProductId });
            }
            _notyf.Error("Đặt hàng không thành công!");
            return RedirectToAction("Detail", "Product", new { id = order.ProductId });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var rs = await _orderService.DeleteOrder(id);
            if (rs is OkResult)
            {
                _notyf.Success("Xóa đơn hàng thành công!");
                return RedirectToAction("Index");
            }
            _notyf.Error("Xóa đơn hàng không thành công!");
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using soppi.Data
@inject SignInManager<ApplicationUser> SignInManager;
@inject UserManager<ApplicationUser> UserManager;



<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - soppi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/soppi.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid ">
                <a class="navbar-brand logo-container" asp-controller="Home" asp-action="Index">
                    <img style="height: 40px; width:100px" src="~/logo.png">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <vc:category></vc:category>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Order" asp-action="Index">Đơn
                                hàng</a>
                        </li>

                    </ul>

                    <div class="row me-lg-5">

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <div class="navbar-collapse col-4" id="navbarNavDarkDropdown">
                                <ul class="navbar-nav">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDarkDropdownMenuLink"
                                            role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Xin chào, @UserManager.GetUserName(User)
                                        </a>
                                        <ul class="dropdown-menu button-logout"
                                            aria-labelledby="navbarDarkDropdownMenuLink">
                                            <li><a class="dropdown-item" asp-controller="Account" asp-action="LogOut">Đăng
                                                    xuất</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        }
                        else
                        {
                            <div class="col-4 text-danger d-flex align-items-center">
                                <a type="button" class="btn btn-info text-light" asp-controller="Account"
                                    asp-action="SignIn">Đăng nhập</a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid main">
        <main role="main">
            <button type="button" class="btn" id="btnTop"><i class="bi bi-arrow-up"></i></button>
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("Notyf")
</body>

</html>

<script>
    $(document).ready(function () {
        $('#btnTop').click(function () {
            $('html, body').animate({ scrollTop: 0 }, 1); // Giảm thời gian cuộn xuống còn 400ms
            return false;
        });
    }); 
</script>