Models/Domain/Category.cs
namespace soppi.Models;

public class Category {
    public int Id { get; set; }
    public string CategoryName { get; set; }
}

Models/ViewModel/Category/CategoryViewModel.cs
namespace soppi.Models.ViewModel {
    public class CategoryViewModel {
        public int Id { get; set; }
        public string CategoryName { get; set; }
    }
}

Areas/Admin/Controllers/CategoryController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using soppi.Interfaces;
using soppi.Models;

namespace soppi.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        private readonly INotyfService _notyf;
        public CategoryController(ICategoryService categoryService, INotyfService notyf)
        {
            _categoryService = categoryService;
            _notyf = notyf;
        }

        public async Task<IActionResult> Index()
        {
            var categories = await _categoryService.GetAll();
            ViewBag.Categories = categories;
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(Category category)
        {
            var rs = await _categoryService.CreateCategory(category);
            if(rs is OkResult)
            {
                _notyf.Success("Thêm danh mục thành công!");
                return RedirectToAction("Index", "Category", new { area = "Admin" });
            }
            _notyf.Error("Tên danh mục đã tồn tại!");
            return RedirectToAction("Index", "Category");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var rs = await _categoryService.DeleteCategory(id);
            if(rs is OkResult)
            {   
                _notyf.Success("Xóa danh mục thành công!");
                return RedirectToAction("Index", "Category", new { area = "Admin" });
            }
            _notyf.Error("Xóa danh mục không thành công!");
            return new BadRequestResult();
        }
    }
}

Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using soppi.Models;
using soppi.Models.ViewModel;
using soppi.Interfaces;

namespace soppi.Controllers {
    public class CategoryController : Controller {
        private ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService) {
            _categoryService = categoryService;
        }

        public async Task<IActionResult> CategoryDropDown() {
            var categories = await _categoryService.GetAll();
            return PartialView("_CategoryDropDown", categories);
        }

        public IActionResult Index() {
            var categories = _categoryService.GetAll().Result;
            return View(categories);
        }

        [HttpGet]
        public IActionResult Add() {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(CategoryViewModel category) {
            await _categoryService.AddCategory(category);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> CategoryProducts(int id, string searchStr) {
            var products = await _categoryService.GetProductsByCategory(id);
            if(string.IsNullOrEmpty(searchStr)) {
                return View(products);
            }
            if (!string.IsNullOrEmpty(searchStr)) {
                products = products.Where(p => p.ProductName.IndexOf(searchStr, StringComparison.OrdinalIgnoreCase) >= 0).ToList();
            }

            return View(products);
        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using soppi.Models.ViewModel;
using soppi.Interfaces;
using AspNetCoreHero.ToastNotification.Abstractions;

public class ProductController : Controller {
    private readonly IProductService _productService;
    private readonly ICategoryService _categoryService;
    private readonly INotyfService _notyf;

    public ProductController(IProductService productService, ICategoryService categoryService, INotyfService notyf) {
        _productService = productService;
        _categoryService = categoryService;
        _notyf = notyf;
    }

    public async Task<IActionResult> Index() {
        var products = await _productService.GetAll();
        return View(products);
    }

    [HttpGet]
    public async Task<IActionResult> Add() {
        var categories = await _categoryService.GetAll();
        ViewBag.Categories = categories;
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> Add(ProductViewModel productViewModel) {
        await _productService.AddProduct(productViewModel);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> Detail(Guid id){
        var product = await _productService.GetProductById(id);
        ViewBag.Product = product;
        return View();
    }
}

Views/Category/Add.cshtml
@model soppi.Models.ViewModel.CategoryViewModel;

<form method="post">
    <div class="mb-3">
        <label for="" class="form-label">Id</label>
        <input type="number" class="form-control" asp-for="Id">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Tên nhãn</label>
        <input type="text" class="form-control" asp-for="CategoryName">
    </div>
    <button type="submit" class="btn btn-primary" asp-action="Add">Submit</button>
</form>

Views/Category/CategoryProducts.cshtml
@model List<soppi.Models.ViewModel.ProductViewModel>

<head>
    <link rel="stylesheet" href="~/Content/css/Home/Index.css">
</head>
<div>
    <div class="d-flex justify-content-end mt-4 me-xl-5">
        <form method="get" asp-action="CategoryProducts" asp-controller="Category" class="d-flex col-lg-2 col-4">
            <input class="form-control me-2" name="searchStr" type="search" placeholder="Tìm kiếm" aria-label="Search"
                id="searchInput">
        </form>
    </div>
    @if (Model.Count == 0)
    {
        <div>
            <h4 class="text-center">Không tìm thấy sản phẩm</h4>
        </div>
    }
    else
    {
        <div class="row mx-xl-5 my-3">
            @foreach (var p in Model)
            {
                <div class="col-lg-2 col-md-4 col-6 my-1 rounded-3">
                    <a class="text-decoration-none text-dark" asp-route-id="@p.Id" asp-controller="Product" asp-action="Detail">
                        <div class="product-outer">
                            <div class="product-image">
                                <img src="@p.Image" alt="Product Image">
                            </div>
                            <div class="product-details m-2">
                                <div class="product-name">@p.ProductName</div>
                                <div class="d-flex justify-content-between">
                                    <div class="product-price price" data-price="@p.Price">@p.Price</div>
                                    <div class="quantity">Số lượng: @p.StockQuantity</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
    }
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        // Lặp qua mỗi phần tử có class là "price"
        $('.price').each(function () {
            // Lấy giá trị số từ thuộc tính data-price
            var price = parseFloat($(this).data('price'));
            // Định dạng lại số với dấu phẩy
            var formattedPrice = price.toLocaleString();
            // Gán lại văn bản đã định dạng vào phần tử
            $(this).text(formattedPrice + " đ");
        });
    });
</script>

Views/Category/Index.cshtml
@model List<soppi.Models.Category>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var category in Model){
                <tr>
                    <td>@category.Id</td>
                    <td>@category.CategoryName</td>
                    <td>
                        <a asp-route-id="@category.Id" asp-action="Detail" class="btn btn-primary">Detail</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>